seleniumhub:
  image: selenium/hub
  ports:
   - 4444:4444

firefoxnode:
  image: selenium/node-firefox-debug
  ports:
    - 4577
  environment:
   - NODE_MAX_INSTANCES=2
   - NODE_MAX_SESSION=2
  links:
   - seleniumhub:hub

chromenode:
  image: selenium/node-chrome-debug
  ports:
    - 4578
  links:
   - seleniumhub:hub
 
 

